### ISSUE TITLE
Ansible problem in step 'apt | Ensure have enough randomness' : cache-update error

### ISSUE THREAD

**Issue by thiagomoreirac** [juju4/ansible-gpgkey_generate#10]
I was struggling with this msg 'Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)', until I tried to comment the update_cache: yes line, as pointed here: https://stackoverflow.com/questions/33563425/ansible-1-9-4-failed-to-lock-apt-for-exclusive-operation/40933352

Apparently, ansible triggers two actions at the same time using apt and the first threat creates the file that locks the 2nd one. 

A possible solution is to create a step to only update cache before. 

Ansible: 2.9.5
Ubuntu: 21.04

**Comment by juju4** [comment]
There is likely something else as working in github actions and in my environment.
nonetheless, splitting task is low impact and if can help, fine.

fixed in https://github.com/juju4/ansible-gpgkey_generate/commit/b35cf7671b789ba1e76258f15979e31fd44e39c5
