### ISSUE TITLE
Fetch privatekey file to orchestrator fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by goetzk** [juju4/ansible-gpgkey_generate#12]
When running on Ubuntu 22.04 retrieving the secret key fails.
```
failed: [example] (item=/etc/pki/gpg/duply/root.priv) => {"ansible_loop_var": "item", "changed": false, "item": "/etc/pki/gpg/duply/root.priv", "msg": "the remote file does not exist, not transferring, ignored"}
```

This appears to be because the private key is no longer available in GPG 2.1 (https://www.gnupg.org/documentation/manuals/gnupg/Unattended-GPG-key-generation.html).

Looking through the code it appears 31423de47ddd4c639cc167fce65fd6c71386bf5b from 2016 was probably fixing this issue for key importing (though its not explicit in the commit message).

Given that Ubuntu < 16.04 and RHEL <7 are out of mainline support; is it time to remove that parameter from the role and the option from gen-key-script?

**Comment by goetzk** [comment]
For the record, I patched the role in my fork to add version constraints matching those added in 31423de47ddd4c639cc167fce65fd6c71386bf5b and the step is correctly skipped.
```
   with_items:
     - "{{ gpg_home }}/{{ gpg_privkeyfile }}"
-  when: gpg_pull is defined and gpg_pull and gpg_pull_privatekey is defined and gpg_pull_privatekey
+  when:
+    - gpg_pull is defined and gpg_pull
+    - gpg_pull_privatekey is defined and gpg_pull_privatekey
+    - not (
+          (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 16) or
+          (ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 7)
+        )
```

**Comment by juju4** [comment]
agreed on cleaning old code
