### ISSUE TITLE
Exported GPG files created from `gpg_generate_user`, not `gpg_user`

### ISSUE THREAD

**Issue by jmcgeheeiv** [juju4/ansible-gpgkey_generate#4]
At the end, a fingerprint file, public key and optionally private key are produced. These files come from `gpg_generate_user`.

If only `juju4.gpgkey_generate` generates keys, the keys and fingerprint extracted from `gpg_user` and `gpg_generate_user` are the same. However, this cannot be guaranteed. The  keys and fingerprint should be extracted directly from `gpg_user`'s keyring.

**Comment by juju4** [comment]
believe related to https://github.com/juju4/ansible-gpgkey_generate/pull/3 
See comment there

**Comment by jmcgeheeiv** [comment]
I am no longer using `ansible-gpgkey_generate` so I leave it to you to leave this issue open or close it.
