### ISSUE TITLE
Sorry, we are in batchmode - can't get input

### ISSUE THREAD

**Issue by tomjohnburton** [juju4/ansible-gpgkey_generate#7]
Getting this running the playbook on a fresh Ubuntu 20.04 

vars
```
    gpg_generator_user: root
    ansible_become_method: sudo
    gpg_realname: '**'
    gpg_useremail: '***'
    gpg_pubkeyfile: '***'
    gpg_privkeyfile: '***'
    gpg_home: '/root'
    gpg_keylength: 4096
    gpg_subkeylength: 4096
    gpg_expire: 0
    gpg_passphrase: null
    gpg_no_log: false

```

error
```
 FAILED! => {"changed": true, "cmd": ["gpg", "--batch", "--gen-key", "/root/.gnupg/gen-key-script-root"], "delta": 
"0:00:00.023266", "end": "2021-04-15 10:58:05.913710", "msg": "non-zero return code", "rc": 2, "start": "2021-04-15 
10:58:05.890444", "stderr": "gpg: Generating a basic OpenPGP key\ngpg: Sorry, we are in batchmode - can't get input",
 "stderr_lines": ["gpg: Generating a basic OpenPGP key", "gpg: Sorry, we are in batchmode - can't get input"], "stdout": "", "stdout_lines": []}

```

**Comment by tomjohnburton** [comment]
I removed this and the problem went away

`gpg_passphrase: null`

**Comment by juju4** [comment]
Per github actions and default vars, it run
https://github.com/juju4/ansible-gpgkey_generate/runs/2434362140?check_suite_focus=true#step:6:466

note that `gpg_passphrase: null` means gpg_passphrase: 'null' meaning the string and not "no passphrase".
it would be more '' or False per https://github.com/juju4/ansible-gpgkey_generate/blob/05b872b11d53b3c8594b932b53eb425a997997d8/templates/gen-key-script#L12

can you try above if I interpreted correctly what you are trying to do?

**Comment by cyberhck** [comment]
> gpg_passphrase: null

if you do this, I believe the default password which is "Passphrase_example.CHANGE_ME!" will be used if I understand correctly.

**Comment by juju4** [comment]
Is this still an issue or can it be closed?

**Comment by juju4** [comment]
Closing old issue. Please reopen if needed
